baseURL = "https://blog.drakehooks.net"
relativeURLs = true
canonifyURLs = true
contentDir = "content"
publishDir = "public"
languageCode = "en-us"
title = "✻ drakeblog"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 2
    style = "dracula"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true