baseURL = 'https://drakehooks.github.io/blog/'
relativeURLs = true
canonifyURLs = true
publishDir = "docs"
languageCode = 'en-us'
title = 'Drake Hooks'
theme = 'dark-mysterious'

[params]
frontimage = "assets/kirby.gif"
